pr:
- master
- develop
- feature/*

pool:
  vmImage: macos-12

variables:
  Configuration: Release
  SDK:
  EOCompliance-Mac: true

jobs:
- job:
  displayName: Puppet iOS
  steps:
  - checkout: self
    submodules: recursive

  - task: Xcode@5
    displayName: 'Sasquatch iOS Puppet Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchPuppet
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'

- job:
  displayName: Puppet Mac Catalyst
  steps:
  - checkout: self
    submodules: recursive

  - task: Xcode@5
    displayName: 'Sasquatch Mac Catalyst Puppet Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchPuppet
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'
      destinationPlatformOption: macOS

- job:
  displayName: Sasquatch iOS
  steps:
  - checkout: self
    submodules: recursive

  - task: Xcode@5
    displayName: 'Sasquatch iOS Objective-C Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchObjC
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'

  - task: Xcode@5
    displayName: 'Sasquatch iOS Swift Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchSwift
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'

- job:
  displayName: Sasquatch macOS
  steps:
  - checkout: self
    submodules: recursive

  - task: Xcode@5
    displayName: 'Sasquatch macOS Objective-C Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchMacObjC
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'

  - task: Xcode@5
    displayName: 'Sasquatch macOS Swift Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchMacSwift
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'

- job:
  displayName: Sasquatch tvOS
  steps:
  - checkout: self
    submodules: recursive

  - task: Xcode@5
    displayName: 'Sasquatch tvOS Objective-C Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchTVObjC
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'

  - task: Xcode@5
    displayName: 'Sasquatch tvOS Swift Archive'
    inputs:
      actions: archive
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: SasquatchTVSwift
      args: 'GCC_TREAT_WARNINGS_AS_ERRORS=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES'
